const homeScreenStyles = {
  container: 'flex-1',
  text: 'text-lg font-bold',
  messageText: '',
  primaryText: 'text-center text-xs ',
  attendanceText: 'text-center text-md font-bold',
  announcementsText: 'text-lg font-medium',
  noAnnouncementsText: 'text-lg font-normal',
  annUserNameseeAllText: 'text-md',
  secondaryText: 'mt-1 text-md font-bold',
  annUserName: 'text-sm font-bold',
  seeAllText: 'text-sm ',
  annUserRole: 'text-xs',
  annDetails: 'text-sm mt-2',
  annTitleView: 'flex flex-row items-center mt-2',
  annTitle: 'text-blue-500 underline',
  userName: 'mt-2 text-sm',
  plus: 'text-xl font-bold text-white',
  userView: 'flex items-center py-8 border-b border-gray-300 bg-black',
  userImg: 'w-[150px] h-[150px] rounded-full',
  parentView: 'w-full h-full bg-white',
  checkoutView: 'h-2/5 bg-black',
  userDetailsView: 'relative h-2/4 pt-4 bg-black',
  userAttendanceView: 'absolute p-4 top-2/4 w-full',
  scrollView: 'mt-[35%]',
  attendanceCardView:
    'bg-white w-full shadow-md shadow-black/25 p-4 rounded-xl my-4',
  shiftText: 'text-center text-sm text-gray-500 mt-1',
  clockInOutView: 'flex flex-row justify-center gap-x-12 items-center mt-4',
  separator: 'text-2xl',
  permissionText: ' text-center text-md mt-4',
  qrContainer: 'flex-col flex-1',
  closeView: 'absolute top-10 right-10 z-10',
  cameraView: 'flex-1 flex flex-col',
  qrBoxView:
    'absolute top-0 bottom-0 left-0 right-0 justify-center items-center',
  qrBoxOutline: 'w-60 h-60 border-2 border-white',
};

export default homeScreenStyles;
