export const TEST_IDS = {
  TEXT: {
    ATTENDANCE: 'home:attendance_txt',
    WORK_SHIFT: 'home:work_shift_txt',
    CHECK_IN: 'home:check_in_txt',
    CHECK_IN_TIME: 'home:check_in_time_txt',
    CHECK_OUT: 'home:check_out_txt',
    CHECK_OUT_TIME: 'home:check_out_time_txt',
    MY_PAYROLL: 'home:my_payroll_txt',
    ABSENCE: 'home:absence_txt',
    TIME_OFF: 'home:time_off_txt',
    APPROVAL: 'home:approval_txt',
    OFFICE_ANNOUNCEMENTS: 'home:office_announcements_txt',
    SEE_ALL_OFFICE_ANNOUNCEMENTS: 'home:office_announcements_see_all_txt',
    NO_ANNOUNCEMENTS: 'home:no_announcements_txt',
    USER_PROFILE_NAME: 'home:user_profile_name_txt',
    USER_PROFILE_DESIGNATION: 'home:user_profile_designation_txt',
    ANNOUNCEMENT_DESCRIPTION: 'home:announcement_description_txt',
    ANNOUNCEMENT_ATTACH_FILE: 'home:announcement_attach_file_txt',
    LOGIN_USER_EMAIL: 'home:login_user_email_txt',
    LOGIN_USER_NAME: 'home:login_user_name_txt',
    HELLO_GOOD_MORNING: 'home:hello_good_morning_txt',
    PLUS: 'home:plus_txt',
    ENTER_YOUR_NAME: 'home:enter_your_name_txt',
    ENTER_YOUR_MESSAGE: 'home:enter_your_message_txt',
  },
  BUTTON: {
    CHECK_IN_CHECK_OUT: 'home:check_in_check_out_btn',
    MY_PAYROLL: 'home:my_payroll_btn',
    ABSENCE: 'home:absence_btn',
    TIME_OFF: 'home:time_off_btn',
    APPROVAL: 'home:approval_btn',
    SUBMIT: 'home:submit_btn',
    ADD_CHAT: 'home:add_chat_btn',
    ADD_GROUP: 'home:add_group_btn',
    PLUS: 'home:plus_btn',
  },
  INPUT: {
    ENTER_YOUR_NAME: 'home:enter_your_name_input',
    ENTER_YOUR_MESSAGE: 'home:enter_your_message_input',
  },
  IMAGE: {
    LOGIN_USER_PROFILE_PICTURE: 'home:profile_picture_img',
    USER_PROFILE_PICTURE: 'home:user_profile_picture_img',
    MY_PAYROLL: 'home:my_payroll_btn',
    ABSENCE: 'home:absence_btn',
    TIME_OFF: 'home:time_off_btn',
    APPROVAL: 'home:approval_btn',
  },
  ERROR: {
    ENTER_YOUR_NAME: 'home:enter_your_name_error',
    ENTER_YOUR_MESSAGE: 'home:enter_your_message_error',
    ENTER_PHONE_NUMBER: 'home:enter_phone_number_error',
  },
};
