export const NAVIGATION_ROUTES = {
  RESET_PASSWORD: 'reset-password',
  OTP: 'otp-screen',
  HOME: 'home-screen',
  LOGIN_IN: 'login-screen',
  REGISTER: 'register-screen',
  FORGOT_PASSWORD_OPTIONS: 'forgot-password-options',
  FORGOT_PASSWORD: 'forgot-password',
  PASSWORD_UPDATED: 'password-updated-screen',
  SETTING: 'setting-screen',
  CHAT: 'chat-screen',
  CHAT_MESSAGES: 'chat-messages-screen',
  CREATE_GROUP: 'create-group-screen',
  USER_PROFILE: 'user-profile-screen',
  GROUP_INFO: 'group-info-screen',
};
